<?php

namespace Rate\CurrencyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RateArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateArchiveRepository extends EntityRepository
{
}
