<?php

namespace Rate\CurrencyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RateCurrentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateCurrentRepository extends EntityRepository
{
}
